Add "Post on Social" section
climatechangemakers/climate-changemakers-act pull request #110
Opened 2021-10-08 02:31 UTC by EvanHahn

![Screenshot](https://user-images.githubusercontent.com/777712/136488369-8827dd43-950e-4ab2-bf6e-14bbccf994af.png)

This pull request implements a basic "Post on Social" section as described in #100.

Some notable technical pieces:

- The backend now returns a JSON object for the pre-composed tweet instead of plain text. This is more extensible and simplifies the frontend code, but I can revert it if needed.
- To enforce tweet validity, I pulled in Twitter's official [tweet-text library](https://github.com/twitter/twitter-text). This is more accurate than a simpler check like `tweet.length > 0 && tweet.length <= 280`, but [it's a nontrivial module](https://bundlephobia.com/package/twitter-text@3.1.0) which we might want to skip for now.
- The pre-composed tweet is loaded as soon as `<TakeActionPage>` mounts so users will probably never see it mid-load, but there's some code to handle that just in case.
- `scrollIntoView` doesn't work if the page is in the background, at least in my testing. This happens when we open a new window to post a tweet. I did a bunch of gymnastics to make this work. I don't love what I came up with, so suggestions are welcome.

A few other things:

- The copy and stylings seemed TBD so I didn't implement this exactly as the designs showed.
- I tried my best to keep the code style consistent, but I fear that I let a little too much of my strange code style through. Please let me know if I deviated too far. Also, I'd love to use an auto-formatter like [Prettier](https://prettier.io/) later on, but that's out of scope for this change.

2021-10-08 02:34 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +        let isCanceled = false;
The API functions don't support cancellation, so this is a simpler way to clean up the effect.

2021-10-08 02:34 UTC, EvanHahn commented on frontend/src/common/lib/twitter.ts
> +    const url = new URL("https://twitter.com/intent/tweet");
`URL` [doesn't work on all browsers](https://caniuse.com/url). Just want to call that out.

2021-10-08 04:12 UTC, kevincianfarini approved these changes

2021-10-08 04:12 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/feature/issue/controller/IssueListController.kt
> +    PreComposedTweetResponse(manager.getPreComposedTweetForIssue(issueId))
Rather than allocating the PreComposedTweetResponse in the controller, i think it should be done from the manager. Thoughts?

2021-10-08 04:12 UTC, kevincianfarini commented on frontend/package.json
> +    "twitter-text": "^3.1.0",
What are the benefits/drawbacks of having this validation live server side? Ideally, this would even be done at the database level, but i am unsure of what validations are being performed.

2021-10-08 04:33 UTC, jacknugent requested changes

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                const done = () => {
Instead of comment, give a more meaningful name, like `updateStateAfterTweetPageOpened`. In that case, would make more sense to move `if (document.hidden)` into this function

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                // We rely on the twitter-text package to enforce lengths, but we have this just in case of a pathologically long string.
Don't think think this comment is necessary

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                onChange={(event) => {
Don't need parens or `{}`:
```javascript
onChange={e => setTweet(e.target.value)}
```

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                onClick={() => {
Don't need `{}`

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +        default:
This default will never happen, can remove and can remove `MissingCaseError`. Also think switch can be replaced entirely with ternary expressions and JSX embedded in main return function --- see above

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +        let isCanceled = false;
What do you mean by this?

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +                setPreComposedTweet({
Why not just have three separate state:
`preComposedTweet` <-- string? that eventually gets `response.data.tweet`
`errorMessage` <-- string? with possible error message
`isLoading` <-- bool for loading pre-composed tweet

Those states are pretty self-explanatory, I think this new type complicates things.

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/common/lib/Loadable.ts
> +  | { status: "failed"; error: ErrorT };
If this is only used in twitter component, easier to just have at top of PostOnSocial component (although I think this type isn't necessary -- see comment above)

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/common/lib/twitter.test.ts
> +describe("Twitter utilities", () => {
Yes testing!!!

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/common/lib/twitter.ts
> +    const url = new URL("https://twitter.com/intent/tweet");
We are not supporting IE11

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/common/api/ClimateChangemakersAPI.ts
> +    await post<unknown>("/log-tweet", { originatingEmailAddress, relatedIssueId, contactedBioguideIds });
Why `unknown`? What does this actually return?

2021-10-08 04:33 UTC, jacknugent commented on frontend/package.json
> +    "lodash": "^4.17.21",
I'm not convinced `lodash` is necessary. ES6 seems to make it mostly obsolete. May potentially remove/keep after we chat on why we need `once` function from lodash

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            let errorMessage = "Your tweet is invalid. Is it too long?";
Even better, just add the ternary logic directly into the Form.Control.Feedback:
```javascript
<Form.Control.Feedback type="invalid" tooltip>
   {weightedLength === 0 ? "You need to enter a tweet."
      : weightedLength > 280 ? `Your tweet is ${weightedLength} characters but 280 is the maximum.`
         : "Your tweet is invalid. Is it too long?";}
</Form.Control.Feedback>
```

2021-10-08 04:33 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                logTweet();
I think it would be clearer to remove this prop and just do the logTweetAPI call within this component

2021-10-08 13:00 UTC, EvanHahn commented on backend/src/main/kotlin/org/climatechangemakers/act/feature/issue/controller/IssueListController.kt
> +    PreComposedTweetResponse(manager.getPreComposedTweetForIssue(issueId))
Up to you. I assumed that the controller, not the manager, should know about the shape of the HTTP response body. But I don't know—lemme know if you want me to move it.

2021-10-08 13:01 UTC, EvanHahn commented on frontend/package.json
> +    "twitter-text": "^3.1.0",
I don't think we should put the validation on the server. Because we're just composing a draft, we'd have to make repeated requests to the server just to validate something Twitter will check anyway.

As an alternative, I could just do basic checks on the length and let the actual Twitter site do the rest.

2021-10-08 13:14 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +        default:
The benefit is to add type checking to ensure that this case will never happen. If we update the type to allow a fourth option, it won't compile, (hopefully) saving us from a bug.

But I'll remove it, as I don't think it's warranted for such a small project.

2021-10-08 13:31 UTC, EvanHahn commented on frontend/src/common/api/ClimateChangemakersAPI.ts
> +    await post<unknown>("/log-tweet", { originatingEmailAddress, relatedIssueId, contactedBioguideIds });
It currently returns a 204 with no response body, so I suppose it'd be `void`. I chose `unknown` because we won't have to keep it in sync with the server. But I'm happy to change it.

2021-10-08 22:12 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/feature/issue/controller/IssueListController.kt
> +    PreComposedTweetResponse(manager.getPreComposedTweetForIssue(issueId))
I'd prefer for this PR to remain consistent with the other managers. However, I do agree that the controllers should be the entities that know about request/response objects.

2021-10-09 14:53 UTC, jacknugent commented
![image](https://user-images.githubusercontent.com/31449177/136662939-9f26e843-807f-43b2-ad0c-6b8b6476a4ec.png)

<img width="397" alt="image" src="https://user-images.githubusercontent.com/31449177/136662936-42ceb779-8bc2-4ec9-8251-cc3063d8dda0.png">

Styling changes to make section look more like the designs:
- Make title pink (I added the “text-pink” class for this)
- Less spacing between title and description
- Add description from design
- Make buttons same color as design
- Slightly more spacing between `<hr />` and title
- Should we stack buttons on mobile? Up to you
- Add icon from Figma

2021-10-10 16:50 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +        let isCanceled = false;
You're right.

More accurately, you don't need to clean up HTTP requests directly, but you _do_ probably want to clean up anything that follows the HTTP request. For example, this component has some problems:

```jsx
function MyComponent({ userId }) {
  const [userName, setUserName] = useState('');

  useEffect(() => {
    setUserName('');
    (async () => {
      setUserName(await fetchUserName(userId));
    })();
  }, [userId]);

  return <div>{userId} has name {userName}</div>;
}
```

There are two issues here.

1. If the component unmounts while a request is in flight, additional things can happen after the component is unmounted.

   In the example above, `setUserName` will be called after the component has unmounted, which is a no-op. That causes React to give the following warning:

   > Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

   This is probably fine, but other side-effects could run later which we don't want. For example, we could kick off a second HTTP request, or update `document.title`, etc.

    I made [a small example app](https://codesandbox.io/s/goofy-panka-wfbb0) to demonstrate this problem.
2. The bigger problem, IMO, is that the UI can get messed up.

   For example, imagine that I change the `userId` prop twice in rapid succession. After the first request finished, we'd see the first user's name until the second request finished. And in a world where the _second_ request finished first, which could happen, we'd see the wrong user name in the UI once everything had settled down.

   I made [another small example app](https://codesandbox.io/s/suspicious-silence-ovxwh) to demonstrate this issue. Try changing the current user rapidly, and you'll see the wrong values in some situations.

If we don't clean up this request and the selected issue changes, we won't cancel the request and we might have the wrong pre-composed tweet.

2021-10-10 16:52 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +            const response = await preComposedTweetAPI(selectedIssueId);
I didn't do this because I wanted the tweet to be loaded by the time the user reached the step, and `<PostOnSocial>` isn't mounted when the page starts. I could:

1. keep things as is.
2. move the request into `<PostOnSocial>`, which would cause users to see a loading state. (Technically, they could see this state today, but they'd have to move through the steps pretty quickly, or be on a spotty internet connection.)
3. keep `<PostOnSocial>` mounted at all times, but don't show it until the step is ready

Any preference?

2021-10-10 18:34 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +                                    const { initiatorEmail: email, legislators } = actionInfo;
Done in 4bb3ac6efd7272eeb9e4f0d5afb646860f365a62.

2021-10-10 18:35 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +                                        // It's okay if this request fails.
Removed in 633dbb22db63558fea0ab322599fe17962685b32.

2021-10-10 18:36 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +                                    logTweetAPI(email, selectedIssue.id, bioguideIds).catch(err => {
Done in 558cc98c3bc9a8b134de0274f84b6645aeeafb8b (didn't wind up using an IIFE).

2021-10-10 19:03 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +    // `scrollIntoView` doesn't work when the window is backgrounded, so we have some complex logic to enqueue a scroll if the window is invisible.
Simplified it with a "Done Tweeting" button, like we discussed "offline", in fae83afac3d2a36dc309111017554bba52f803ae.

2021-10-10 19:05 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            const onClickSendTweet = once(() => {
Done. Sidestepped this in fae83afac3d2a36dc309111017554bba52f803ae.

2021-10-10 19:05 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                const done = () => {
Done; sidestepped this in fae83afac3d2a36dc309111017554bba52f803ae.

2021-10-10 19:05 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                document.addEventListener('visibilitychange', onVisibilityChange, false);
Removed in fae83afac3d2a36dc309111017554bba52f803ae.

2021-10-10 19:06 UTC, EvanHahn commented on frontend/package.json
> +    "lodash": "^4.17.21",
Removed it in fae83afac3d2a36dc309111017554bba52f803ae.

2021-10-10 19:20 UTC, EvanHahn commented on frontend/package.json
> +    "twitter-text": "^3.1.0",
Uninstalled the library and used a simpler check in 49a640ace8194f0573b71dc43f3e631132661890.

2021-10-10 19:21 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            let errorMessage = "Your tweet is invalid. Is it too long?";
Done in 49a640ace8194f0573b71dc43f3e631132661890.

2021-10-10 19:21 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            // We always render an error message, even if we don't display it.
Removed in 49a640ace8194f0573b71dc43f3e631132661890.

2021-10-10 19:21 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                // We rely on the twitter-text package to enforce lengths, but we have this just in case of a pathologically long string.
Removed in 29b6726cd579ec1f7cf3a057498e91767102c869.

2021-10-10 19:24 UTC, EvanHahn commented on frontend/src/common/api/ClimateChangemakersAPI.ts
> +}
Done in 64919a7aded3327dffe4198d44ce28ec21fa9d73.

2021-10-10 19:29 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                <Form as="div">
Done in 9705a527f2713f86e8cebdc4f6e96e7628ac7a3a.

2021-10-10 19:30 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +        }
Done in 7fee34b3110da84860e008413c5d84094dc4f1da.

2021-10-10 19:31 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                onChange={(event) => {
Done in b1009c3e50f00794a03ccfd2d7b84df840d9243e.

2021-10-10 19:32 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +        default:
Removed it in 9705a527f2713f86e8cebdc4f6e96e7628ac7a3a.

2021-10-10 19:33 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                                onClick={() => {
Sidestepped in 9705a527f2713f86e8cebdc4f6e96e7628ac7a3a.

2021-10-10 19:34 UTC, EvanHahn commented on frontend/src/common/api/ClimateChangemakersAPI.ts
> +    await post<unknown>("/log-tweet", { originatingEmailAddress, relatedIssueId, contactedBioguideIds });
Sidestepped this in 64919a7aded3327dffe4198d44ce28ec21fa9d73.

2021-10-10 19:42 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +                logTweet();
Done in d374a422ee80c23cff3d2f2bbfc501b74cff703c.

2021-10-10 19:51 UTC, jacknugent requested changes

2021-10-11 17:50 UTC, jacknugent approved these changes
Just two small suggestions, otherwise looks good

2021-10-11 17:50 UTC, jacknugent commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            } catch (err: unknown) {
Can you just do:
```javascript
const response = await logTweetAPI(actionInfo.initiatorEmail, selectedIssue.id, bioguideIds));
if(response.error)
     console.warn(error);
```

2021-10-11 17:50 UTC, jacknugent commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +    } = useSWR<{ tweet: string }, string>(() => (selectedIssueId !== undefined ? `/issues/${selectedIssueId}/precomposed-tweet` : null), fetcher);
Slightly simpler ternary syntax:
```javascript
!selectedIssueId ? null : `/issues/${selectedIssueId}/precomposed-tweet`
```

2021-10-11 19:12 UTC, jacknugent commented on frontend/src/Pages/TakeAction/TakeActionPage.tsx
> +    } = useSWR<{ tweet: string }, string>(() => (selectedIssueId !== undefined ? `/issues/${selectedIssueId}/precomposed-tweet` : null), fetcher);
Ok

2021-10-12 02:15 UTC, EvanHahn commented on frontend/src/Pages/TakeAction/PostOnSocial.tsx
> +            } catch (err: unknown) {
Done in 2bc151a4f4a414e2ede1d5fbae121aa16159979c.

2021-10-12 02:16 UTC, EvanHahn commented
Addressed all comments and merged `trunk`. I think this should be ready to go, though in the future we'll need to send a few more things to the precomposed tweet endpoint.

2021-10-12 02:22 UTC, merged