Check if current user is a Changemaker
climatechangemakers/climate-changemakers-act pull request #180
Opened 2021-11-27 01:26 UTC by kevincianfarini

This commit adds an intergration with Airtable, our user management CRM.

When in production, this commit will query Airtable's API for user
enrollment. Otherwise, this commit includes a `FakeAirtableService`
which doesn't actually query Airtable. This can be controlled by the
environment variable `IS_PRODUCTION`.

Closes #125

2021-11-27 16:00 UTC, EvanHahn requested changes
LGTM but I think we wanna rework some of the Airtable retry logic. Left a more specific comment about that.

2021-11-27 16:01 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/di/Qualifiers.kt
> +annotation class AirTable
ah yes, I have no strong feelings on this. Will change.

2021-11-27 16:02 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/feature/membership/service/AirtableService.kt
> +  ): AirtableResponse
I thought about that too. I'm very happy to create a development/staging airtable environment that mirrors the prod one!

2021-11-28 05:49 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/di/EnvironmentModule.kt
> +  fun providesIsProduction() = getEnvironmentVariable(EnvironmentVariable.IsProduction).toBooleanStrict()
This is a moot point now that we have a staging Airtable base. Otherwise, I agree.

2021-11-29 13:56 UTC, kevincianfarini commented on backend/src/main/kotlin/org/climatechangemakers/act/feature/membership/service/AirtableService.kt
> +  ): AirtableResponse
@EvanHahn I've added retries! Currently the `withRetry` function implements trivial exponential backoff. I decided not to add jitter to this, and thought caching of any sort was too heavy handed for our purposes for the time being. We can always revisit later (and hopefully just move our data out of Airtable). 

There's one outstanding unit test for `withRetry` that actually tests that time mechanics are working correctly. This is a `TODO`, but I plan on getting to that later today. 

Everything else is ready for review.

2021-11-29 14:05 UTC, EvanHahn approved these changes

2021-11-29 14:05 UTC, EvanHahn commented on backend/src/test/kotlin/org/climatechangemakers/act/feature/membership/service/FakeAirtableService.kt
> +class FakeAirtableService : AirtableService {
Is this used anymore? (Feel free to ignore this comment if it is.)

2021-11-29 14:06 UTC, kevincianfarini commented on backend/src/test/kotlin/org/climatechangemakers/act/feature/membership/manager/AirtableMembershipManagerTest.kt
> +    val response = withRetry(2) { attempt ->
This...doesn't test the manager? 

Drink some coffee and revisit.

2021-11-29 14:07 UTC, kevincianfarini commented on backend/src/test/kotlin/org/climatechangemakers/act/feature/membership/service/FakeAirtableService.kt
> +class FakeAirtableService : AirtableService {
yes! It's used for testing. It's now exclusive to the test sourceset.

2021-11-29 17:41 UTC, merged